[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version =  "shanghai"
solc_version = "0.8.28"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
sort_imports = true

[rpc_endpoints]
optimism = "${RPC_OPTIMISM}"
base = "${RPC_BASE}"

[etherscan]
optimistic = { key = "${OPTIMISTIC_API_KEY}" }
baseScan = { key = "${BASESCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
